---
server:
  log_level: debug
  http_addr: "0.0.0.0:8080"
  https_addr: "0.0.0.0:8443"
  tls_config:
    www.example.com:
      cert_path: example.cert
      key_path: example.key
admin:
  enable: true
  adminapi_addr: "127.0.0.1:8000"
  users:
    - username: admin
      password: admin
routes:
  - id: hello
    name: hello
    desc: ""
    uris:
      - /hello
    upstream_id: upstream-001
    matcher: ""
    priority: 0
    plugins: {}
  - id: hello-to-tom
    name: hello-to-tom
    desc: ""
    uris:
      - /hello/*
    upstream_id: upstream-002
    matcher: "Query('name', 'tom')"
    priority: 100
    plugins:
      path_rewrite:
        enable: true
        regex_replace:
          - /hello/(.*)
          - /$1
      traffic_split:
        enable: true
        rules:
          - matcher: "PathRegexp('/hello/world/\\(.*\\)')"
            upstream_id: hello-to-tom
upstreams:
  - id: upstream-001
    name: upstream-001
    desc: ""
    endpoints:
      - addr: "127.0.0.1:5000"
        weight: 1
    strategy: random
    is_https: false
    health_check:
      slow_threshold: 0
      timeout: 0
      path: ""
  - id: upstream-002
    name: upstream-002
    desc: ""
    endpoints:
      - addr: "127.0.0.1:5000"
        weight: 1
    strategy: weighted
    is_https: false
    health_check:
      slow_threshold: 0
      timeout: 0
      path: ""
