---
server:
  log_level: debug
  http_addr: "0.0.0.0:5000"
  https_addr: "0.0.0.0:443"
  tls_config:
    www.example.com:
      cert_path: example.cert
      key_path: example.key
routes:
  - name: hello
    uris:
      - /hello
    matcher: ""
    upstream_name: upstream-001
  - name: hello-to-tom
    uris:
      - /hello
    matcher: "Query('name', 'tom')"
    upstream_name: upstream-002
upstreams:
  - name: upstream-001
    endpoints:
      - addr: "127.0.0.1:8080"
        weight: 1
    strategy: random
  - name: upstream-002
    endpoints:
      - addr: "127.0.0.1:8090"
        weight: 1
    strategy: random
